# Generated by Django 5.2.6 on 2025-09-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyledger',
            old_name='budget_allocated',
            new_name='base_budget',
        ),
    ]
