# Generated by Django 5.2.6 on 2025-10-01 16:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0003_category_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='#3B82F6', help_text='Hex color like #AABBCC', max_length=7, validators=[django.core.validators.RegexValidator(message='Color must be a hex code like #AABBCC', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')]),
        ),
    ]
