# Generated by Django 5.2.6 on 2025-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0004_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyledger',
            name='is_manual_override',
            field=models.BooleanField(default=False),
        ),
    ]


